services:
  backend:
    build: ../backend
    links:
      - neo4j
    ports:
      - "8080:8080"
    volumes:
      - import:/import
    depends_on:
      neo4j:
        condition: service_healthy
    healthcheck:
        test: wget http://localhost:8080/api/branch/get_branches_without_warehouse || exit 1
        interval: 1s
        timeout: 10s
        retries: 20
        start_period: 10s
  frontend:
    build: ../frontend
    links:
      - backend
    ports:
      - "3000:3000"
    depends_on:
      backend:
        condition: service_healthy
  neo4j:
    image: neo4j:5.14.0
    expose:
      - "7474"
      - "7687"
    ports:
      - "7474:7474"
      - "7687:7687"
    environment:
      - NEO4J_AUTH=none
      - NEO4J_apoc_export_file_enabled=true
      - NEO4J_apoc_import_file_enabled=true
      - NEO4J_apoc_import_file_use__neo4j__config=true
      - NEO4J_PLUGINS=["apoc"] 
    volumes:
      - data:/data
      - import:/import
    healthcheck:
        test: wget http://localhost:7474 || exit 1
        interval: 1s
        timeout: 10s
        retries: 20
        start_period: 3s
volumes:
  data:
  import:
networks:
  neo4j-tier:
  back-tier: